services:
  db:
    image: "mysql:8.0-debian"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_ROOT_PASSWORD=password
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 2
      start_period: 30s
