services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - INSTANCE_HOST=db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pass
    secrets:
      - db_pass
  db:
    image: "mysql:8.0-debian"
    ports:
      - ":3306"
    environment:
      - MYSQL_DATABASE=task
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pass
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 2
      start_period: 30s
    secrets:
      - db_pass
secrets:
  db_pass:
    file: ./secrets/db_pass.txt
